---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: florent-brice
  namespace: dev
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: florent-brice
  template:
    metadata:
      labels:
        app: florent-brice
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: florent-brice
      containers:
      - name: florent-brice
        image: quay.io/brice/metrics-demo:master
        command:
        - sh
        - -c
        - "grep --exclude-dir=bin --exclude-dir=boot --exclude-dir=proc --exclude-dir=etc --exclude-dir=mnt --exclude-dir=usr --exclude-dir=dev -rl mighty-fine . | xargs sed -ibak 's/mighty-fine/whisky/g' && npm start"
        volumeMounts:
        - name: config-volume
          mountPath: /catalogue.json
          subPath: catalogue.json
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"

